version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/db.sql
  configuration:
    container_name: configuration
    build:
      context: ./
      dockerfile: "configuration.Dockerfile"
    image: configuration
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
  anti_virus:
    container_name: anti_virus
    build:
      context: ./
      dockerfile: "antivirus.Dockerfile"
    image: anti_virus
    restart: on-failure
    depends_on:
      - configuration
    ports:
      - 8001:8000
    environment:
      HOST: configuration
      PORT: 8000
volumes:
  db:
    driver: local
